services:
  - type: web
    name: flask-app
    env: docker
    dockerfilePath: Dockerfile
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: EMAIL_SENDER
        value: nwekee125@gmail.com
      - key: EMAIL_PASSWORD
        value: wkxefsuonoulinca
      - key: EMAIL_RECEIVER
        value:  maxwell202201@gmail.com
